
import image1 from "@/assets/img/apartment-flat-new-build-alcantarilla-pueblo_11920_md.jpg"
import image2 from "@/assets/img/apartment-flat-new-build-archena-villanueva-del-rio-segura_19968_md.jpg"
import image3 from "@/assets/img/bungalow-new-build-castalla-castalla-internacional_27318_md.jpg"
import image4 from "@/assets/img/apartment-flat-new-build-aguilas-collado_4616_md.jpg"
import image5 from "@/assets/img/apartment-flat-new-build-aguilas-centro_25188_md.jpg"
import image6 from "@/assets/img/apartment-flat-resale-benidorm-levante_22598_md.jpg"
import image7 from "@/assets/img/apartment-flat-new-build-alcantarilla-pueblo_11909_md.jpg"
import image8 from "@/assets/img/penthouse-new-build-aguilas-centro_25163_md.jpg"
import image9 from "@/assets/img/townhouse-new-build-bigastro-bigastro_4272_md.jpg"
import image10 from "@/assets/img/apartment-flat-new-build-algorfa-pueblo_3923_md.jpg"
import image11 from "@/assets/img/apartment-flat-new-build-relleu-pueblo_2586_md.jpg"
import image12 from "@/assets/img/villa-new-build-altea-altea-hills_2124_md.jpg"
import image13 from "@/assets/img/villa-new-build-altea-altea-hills_2074_md.jpg"
import image14 from "@/assets/img/duplex-resale-finestrat-camporrosso-village_23324_md.jpg"
import image15 from "@/assets/img/apartment-flat-resale-torrevieja-playa-de-los-locos_27898_md.jpg"
import image16 from "@/assets/img/villa-new-build-finestrat-finestrat_23011_md.jpg"
import image17 from "@/assets/img/villa-new-build-altea-sierra-de-altea_1664_md.jpg"

export const API = [
  {
    id: 1,
    title: 'Sunny Apartment',
    type: 'Apartment / flat',
    images: [image1, image2, image3],
    badges: ['SEA VIEW', 'MODERN KITCHEN'],
    size: '120m2',
    location: "Alcantarilla · pueblo · Murcia",
    plot: '—',
    bedrooms: '3',
    bathrooms: '2',

    parking: 'Yes',
    reference: 'APT-10001',
    price: 250000,
    town: { value: "8141", label: "Alcantarilla" },
    status: ['New Build', 'Resale'],
    pool: false
  },
  {
    id: 2,
    title: 'Cozy Bungalow',
    type: 'Bungalow',
    images: [image2, image3, image4],
    badges: ['PRIVATE GARDEN'],
    size: '140m2',
    plot: '500m2',
    location: "Archena · Villanueva del Rio Segura · Murcia",
    bedrooms: '4',
    bathrooms: '2',
    parking: 'No',
    reference: 'BUN-10002',
    price: 350000,
    town: { value: "8208", label: "Archena" },
    status: ['Resale'],
    pool: true
  
  },
  {
    id: 3,
    title: 'Modern Villa',
    type: 'Villa',
    images: [image3, image4, image5],
    badges: ['PRIVATE SWIMMING POOL', 'PRIVATE FOREST'],
    size: '431m2',
    plot: '1.670m2',
    location: "Castalla · Castalla Internacional · Alicante",
    bedrooms: '6',
    bathrooms: '6',
    parking: 'No',
    reference: 'VIL-10003',
    price: 1390000,
    town: { value: "8173", label: "Castalla" },
    status: ['New Build', 'Resale'],
    pool: true  
  },
  {
    id: 4,
    title: 'Penthouse with Sea View',
    type: 'Penthouse',
    images: [image4, image5, image6],
    badges: ['TERRACE', 'SEA VIEW'],
    size: '180m2',
    plot: '—',
    location: "Aguilas · Centro · Murcia",
    bedrooms: '3',
    bathrooms: '2',
    pool: false,
    parking: 'Yes',
    reference: 'PEN-10004',
    price: 450000,
    town: { value: "8155", label: "Aguilas" },
    status: ['Resale'],
    pool: false
  },
  {
    id: 5,
    title: 'Luxury Townhouse',
    type: 'Townhouse',
    images: [image5, image6, image7],
    badges: ['PRIVATE GARDEN', 'GREAT LOCATION'],
    size: '200m2',
    plot: '300m2',
    location: "Aguilas · Collado · Murcia",
    bedrooms: '4',
    bathrooms: '3',
    pool: false,
    parking: 'Yes',
    reference: 'TOW-10005',
    price: 320000,
    town: { value: "8258", label: "Aguilas" },
    status: ['Resale'],
    pool: false
  },
  {
    id: 6,
    title: 'Coastal Bungalow',
    type: 'Bungalow',
    images: [image6, image7, image8],
    badges: ['SEA VIEW', 'PRIVATE TERRACE'],
    size: '150m2',
    plot: '600m2',
    location: "Archena · Villanueva del Rio Segura · Murcia",
    bedrooms: '3',
    bathrooms: '2',
    parking: 'No',
    reference: 'BUN-10006',
    price: 400000,
    town: { value: "8206", label: "Archena" },
    status: ['New Build'],
    pool:true
  },
  {
    id: 7,
    title: 'New Construction Villa',
    type: 'Villa',
    images: [image7, image8, image9],
    badges: ['PRIVATE SWIMMING POOL', 'MODERN DESIGN'],
    size: '350m2',
    plot: '1.200m2',
    bedrooms: '5',
    location: "Aguilas · Centro · Murcia",
    bathrooms: '4',
    parking: 'No',
    reference: 'VIL-10007',
    price: 980000,
    town: { value: "8261", label: "Aguilas" },
    status: ['New Build', 'Resale'],
    pool:true
  },
  {
    id: 8,
    title: 'Elegant Apartment',
    type: 'Apartment / flat',
    images: [image8, image9, image10],
    badges: ['CITY CENTER', 'TERRACE'],
    size: '130m2',
    plot: '—',
    location: "Benidorm · Levante ·Alicante",
    bedrooms: '2',
    bathrooms: '2',
    pool: false,
    parking: 'Yes',
    reference: 'APT-10008',
    price: 220000,
    town: { value: "8243", label: "Benidorm" },
    status: ['Resale'],
    
  },
  {
    id: 9,
    title: 'Spacious Duplex',
    type: 'Duplex',
    images: [image9, image10, image11],
    badges: ['TERRACE', 'PARKING'],
    size: '200m2',
    plot: '—',
    location: "Alcantarilla · pueblo · Murcia",
    bedrooms: '4',
    bathrooms: '3',
    pool: false,
    parking: 'Yes',
    reference: 'DUP-10009',
    price: 380000,
    town: { value: "8273", label: "Alcantarilla" },
    status: ['Resale'],
    
  },
  {
    id: 10,
    title: 'Modern Penthouse',
    type: 'Penthouse',
    images: [image10, image11, image12],
    badges: ['ROOFTOP TERRACE', 'SEA VIEW'],
    size: '170m2',
    plot: '—',
    location: "Aguilas · Centro · Murcia",
    bedrooms: '3',
    bathrooms: '2',
    pool: false,
    parking: 'Yes',
    reference: 'PEN-10010',
    price: 420000,
    town: { value: "8143", label: "Aguilas" },
    status: ['New Build', 'Resale'],
    
  },
  {
    id: 11,
    title: 'Luxury Townhouse',
    type: 'Townhouse',
    images: [image11, image12, image13],
    badges: ['PRIVATE GARDEN', 'POOL'],
    size: '220m2',
    plot: '350m2',
    location: "Bigastro · Alicante",
    bedrooms: '4',
    bathrooms: '3',
    parking: 'No',
    reference: 'TOW-10011',
    price: 360000,
    town: { value: "8248", label: "Bigastro" },
    status: ['New Build'],
    pool:true
  },
  {
    id: 12,
    title: 'Cozy Villa',
    type: 'Villa',
    images: [image12, image13, image14],
    badges: ['PRIVATE POOL', 'GARDEN'],
    size: '300m2',
    plot: '1.000m2',
    location: "Algorfa · Pueblo ·Alicante",
    bedrooms: '5',
    bathrooms: '4',
    parking: 'No',
    reference: 'VIL-10012',
    price: 780000,
    town: { value: "8277", label: "Algorfa" },
    status: ['Resale'],
    pool:true
  },
  {
    id: 13,
    title: 'Seaside Bungalow',
    type: 'Bungalow',
    images: [image13, image14, image15],
    badges: ['SEA VIEW', 'PRIVATE TERRACE'],
    size: '160m2',
    plot: '450m2',
    location: "Relleu · pueblo · Alicante",
    bedrooms: '3',
    bathrooms: '2',
    parking: 'Yes',
    reference: 'BUN-10013',
    price: 390000,
    town: { value: "8246", label: "Relleu" },
    status: ['Resale'],
    pool:true
  },
  {
    id: 14,
    title: 'Modern Apartment',
    type: 'Apartment / flat',
    images: [image14, image15, image16],
    badges: ['CITY CENTER', 'BALCONY'],
    size: '110m2',
    plot: '—',
    location: "Denia · Pueblo · Alicante",
    bedrooms: '2',
    bathrooms: '1',
    pool: false,
    parking: 'Yes',
    reference: 'APT-10014',
    price: 210000,
    town: { value: "8144", label: "Denia" },
    status: ['Resale'],
    
  },
  {
    id: 15,
    title: 'Luxury Villa',
    type: 'Villa',
    images: [image15, image16, image17],
    badges: ['PRIVATE POOL', 'MODERN DESIGN', 'SEA VIEW'],
    size: '450m2',
    plot: '1.800m2',
    location: "Jumilla · Pueblo · Alicante",
    bedrooms: '6',
    bathrooms: '6',
    pool: true,
    parking: 'Yes',
    reference: 'VIL-10015',
    price: 1500000,
    town: { value: "8281", label: "Jumilla", },
    status: ['New Build'],
    reference: 'VIL-10015',
  
  }
]

export const properties = {
  towns: [
    { value: "Abanilla", label: "Abanilla", },
    { value: "Aguilas", label: "Aguilas", },
    { value: "Alcantarilla", label: "Alcantarilla", },
    { value: "Alfas del Pí", label: "Alfas del Pí", },
    { value: "Algorfa", label: "Algorfa", },
    { value: "Alhama De Murcia", label: "Alhama De Murcia", },
    { value: "Alicante", label: "Alicante", },
    { value: "Almerimar", label: "Almerimar", },
    { value: "Almoradí", label: "Almoradí", },
    { value: "Altea", label: "Altea", },
    { value: "Archena", label: "Archena", },
    { value: "Aspe", label: "Aspe", },
    { value: "Avileses", label: "Avileses", },
    { value: "Baños y Mendigo", label: "Baños y Mendigo", },
    { value: "Benidorm", label: "Benidorm", },
    { value: "Benijofar", label: "Benijofar", },
    { value: "Benissa", label: "Benissa", },
    { value: "Benitachell", label: "Benitachell", },
    { value: "Bigastro", label: "Bigastro", },
    { value: "Busot", label: "Busot", },
    { value: "Cabo de Palos", label: "Cabo de Palos", },
    { value: "Calasparra", label: "Calasparra", },
    { value: "Calpe", label: "Calpe", },
    { value: "Cartagena", label: "Cartagena", },
    { value: "Castalla", label: "Castalla", },
    { value: "Ciudad Quesada", label: "Ciudad Quesada", },
    { value: "Cox", label: "Cox", },
    { value: "Cuevas Del Almanzora", label: "Cuevas Del Almanzora", },
    { value: "Daya Nueva", label: "Daya Nueva", },
    { value: "Denia", label: "Denia", },
    { value: "Dolores", label: "Dolores", },
    { value: "El Verger", label: "El Verger", },
    { value: "Els Poblets", label: "Els Poblets", },
    { value: "Finestrat", label: "Finestrat", },
    { value: "Formentera del Segura", label: "Formentera del Segura", },
    { value: "Fortuna", label: "Fortuna", },
    { value: "Fuente Álamo", label: "Fuente Álamo", },
    { value: "Godella", label: "Godella", },
    { value: "Gran Alacant", label: "Gran Alacant", },
    { value: "Guardamar del Segura", label: "Guardamar del Segura", },
    { value: "Hondón de las Nieves", label: "Hondón de las Nieves", },
    { value: "Jávea Xàbia", label: "Jávea Xàbia", },
    { value: "Jumilla", label: "Jumilla", },
    { value: "La Manga Club", label: "La Manga Club", },
    { value: "La Manga del Mar Menor", label: "La Manga del Mar Menor", },
    { value: "La Marina", label: "La Marina", },
    { value: "La Nucía", label: "La Nucía", },
    { value: "La Romana", label: "La Romana", },
    { value: "Los Alcazares", label: "Los Alcazares", },
    { value: "Los Belones", label: "Los Belones", },
    { value: "Los Montesinos", label: "Los Montesinos", },
    { value: "Los Nietos", label: "Los Nietos", },
    { value: "Los Urrutias", label: "Los Urrutias", },
    { value: "Mojacar", label: "Mojacar", },
    { value: "Molina De Segura", label: "Molina De Segura", },
    { value: "Monforte del Cid", label: "Monforte del Cid", },
    { value: "Moraira_Teulada", label: "Moraira_Teulada", },
    { value: "Moratalla", label: "Moratalla", },
    { value: "Mutxamel", label: "Mutxamel", },
    { value: "Orihuela", label: "Orihuela", },
    { value: "Orihuela Costa", label: "Orihuela Costa", },
    { value: "Orxeta", label: "Orxeta", },
    { value: "Pilar de la Horadada", label: "Pilar de la Horadada", },
    { value: "Pinoso", label: "Pinoso", },
    { value: "Polop", label: "Polop", },
    { value: "Puerto de Mazarron", label: "Puerto de Mazarron", },
    { value: "Relleu", label: "Relleu", },
    { value: "Rojales", label: "Rojales", },
    { value: "San Fulgencio", label: "San Fulgencio", },
    { value: "San Javier", label: "San Javier", },
    { value: "San Juan Alicante", label: "San Juan Alicante", },
    { value: "San Juan de los Terreros", label: "San Juan de los Terreros", },
    { value: "San Miguel de Salinas", label: "San Miguel de Salinas", },
    { value: "San Pedro del Pinatar", label: "San Pedro del Pinatar", },
    { value: "Sangonera la Verde", label: "Sangonera la Verde", },
    { value: "Santa Pola", label: "Santa Pola", },
    { value: "Santiago de la Ribera", label: "Santiago de la Ribera", },
    { value: "Sucina", label: "Sucina", },
    { value: "Torre Pacheco", label: "Torre Pacheco", },
    { value: "Torrevieja", label: "Torrevieja", },
    { value: "Vera", label: "Vera", },
    { value: "Vera Playa", label: "Vera Playa", },
    { value: "Villajoyosa", label: "Villajoyosa", },
    { value: "Xeresa", label: "Xeresa", },
    { value: "Yecla", label: "Yecla", },
  ]
  ,
  zones: [
    { value: "Aguamarina", label: "Aguamarina" },
    { value: "Aguas Nuevas", label: "Aguas Nuevas" },
    { value: "Alberca", label: "Alberca" },
    { value: "Alenda Golf", label: "Alenda Golf" },
    { value: "Almerimar", label: "Almerimar" },
    { value: "Altaona Golf", label: "Altaona Golf" },
    { value: "Altea Hills", label: "Altea Hills" },
    { value: "Altea La Vella", label: "Altea La Vella" },
    { value: "Altos De La Marquesa", label: "Altos De La Marquesa" },
    { value: "Altos del Sol", label: "Altos del Sol" },
    { value: "Andrago", label: "Andrago" },
    { value: "Arabí", label: "Arabí" },
    { value: "Arenal Bol", label: "Arenal Bol" },
    { value: "Avda. America", label: "Avda. America" },
    { value: "Avenida del Puerto", label: "Avenida del Puerto" },
    { value: "Avileses", label: "Avileses" },
    { value: "Balcón De Finestrat", label: "Balcón De Finestrat" },
    { value: "Balsicas", label: "Balsicas" },
    { value: "Barranc Fondo", label: "Barranc Fondo" },
    { value: "Benalua", label: "Benalua" },
    { value: "Benijofar", label: "Benijofar" },
    { value: "Benimar", label: "Benimar" },
    { value: "Benissa", label: "Benissa" },
    { value: "Bigastro", label: "Bigastro" },
    { value: "Blue Lagoon", label: "Blue Lagoon" },
    { value: "Bonalba-cotoveta", label: "Bonalba-cotoveta" },
    { value: "Buenavista", label: "Buenavista" },
    { value: "Cabo Roig", label: "Cabo Roig" },
    { value: "Cala de Finestrat", label: "Cala de Finestrat" },
    { value: "Cala Finestrat", label: "Cala Finestrat" },
    { value: "Cala La Fustera", label: "Cala La Fustera" },
    { value: "Cala Medina", label: "Cala Medina" },
    { value: "Calpe", label: "Calpe" },
    { value: "Camino Del Prado", label: "Camino Del Prado" },
    { value: "Campana Garden", label: "Campana Garden" },
    { value: "Campo de San Juan", label: "Campo de San Juan" },
    { value: "Campoamor", label: "Campoamor" },
    { value: "Campolivar", label: "Campolivar" },
    { value: "Camporrosso Village", label: "Camporrosso Village" },
    { value: "Cañada de la Leña", label: "Cañada de la Leña" },
    { value: "Castalla Internacional", label: "Castalla Internacional" },
    { value: "Centro", label: "Centro" },
    { value: "Cerro Del Sol", label: "Cerro Del Sol" },
    { value: "Ciudad Quesada", label: "Ciudad Quesada" },
    { value: "Collado", label: "Collado" },
    { value: "Cometa III", label: "Cometa III" },
    { value: "Condado De Alhama", label: "Condado De Alhama" },
    { value: "Condado De Alhama Golf Resort", label: "Condado De Alhama Golf Resort" },
    { value: "Coto Riñales", label: "Coto Riñales" },
    { value: "Cotoveta", label: "Cotoveta" },
    { value: "Cucarres", label: "Cucarres" },
    { value: "Cuidad Quesada", label: "Cuidad Quesada" },
    { value: "Cumbre Del Sol", label: "Cumbre Del Sol" },
    { value: "Cumbres Del Sol", label: "Cumbres Del Sol" },
    { value: "Daya Nueva", label: "Daya Nueva" },
    { value: "Dehesa de campoamor", label: "Dehesa de campoamor" },
    { value: "Desert Springs Golf Club", label: "Desert Springs Golf Club" },
    { value: "Doña Pepa", label: "Doña Pepa" },
    { value: "El Alba", label: "El Alba" },
    { value: "El Albir", label: "El Albir" },
    { value: "El Barranco", label: "El Barranco" },
    { value: "El Chaparral", label: "El Chaparral" },
    { value: "El Oasis", label: "El Oasis" },
    { value: "El Pinet", label: "El Pinet" },
    { value: "El Playazo", label: "El Playazo" },
    { value: "El Portet", label: "El Portet" },
    { value: "El Raso", label: "El Raso" },
    { value: "El Salero", label: "El Salero" },
    { value: "El Tesoro", label: "El Tesoro" },
    { value: "El Verger", label: "El Verger" },
    { value: "Els Secans", label: "Els Secans" },
    { value: "Empedrola", label: "Empedrola" },
    { value: "Entre golf", label: "Entre golf" },
    { value: "Escandinavia", label: "Escandinavia" },
    { value: "Estacion de autobuses", label: "Estacion de autobuses" },
    { value: "Estrella De Mar", label: "Estrella De Mar" },
    { value: "Euro Roda", label: "Euro Roda" },
    { value: "Fanadix", label: "Fanadix" },
    { value: "Finestrat", label: "Finestrat" },
    { value: "Finestrat Hills", label: "Finestrat Hills" },
    { value: "Florida Baja", label: "Florida Baja" },
    { value: "Formentera del Segura", label: "Formentera del Segura" },
    { value: "Franc Espinós", label: "Franc Espinós" },
    { value: "Fustera", label: "Fustera" },
    { value: "Galeretes", label: "Galeretes" },
    { value: "Golf Bahia", label: "Golf Bahia" },
    { value: "Golf La Marquesa (Ciudad Quesada)", label: "Golf La Marquesa (Ciudad Quesada)" },
    { value: "Gran Alacant", label: "Gran Alacant" },
    { value: "Gran Sol", label: "Gran Sol" },
    { value: "Guardamar", label: "Guardamar" },
    { value: "Guardamar Del Segura", label: "Guardamar Del Segura" },
    { value: "Habaneras", label: "Habaneras" },
    { value: "Hoya de los Patos", label: "Hoya de los Patos" },
    { value: "Isla Del Fraile", label: "Isla Del Fraile" },
    { value: "L´Estanyó (Marinas)", label: "L´Estanyó (Marinas)" },
    { value: "La Alberca", label: "La Alberca" },
    { value: "La Canalosa", label: "La Canalosa" },
    { value: "La Capitana", label: "La Capitana" },
    { value: "La Ciñuelica", label: "La Ciñuelica" },
    { value: "La Concha", label: "La Concha" },
    { value: "La Finca Golf", label: "La Finca Golf" },
    { value: "La Font", label: "La Font" },
    { value: "La Herrada", label: "La Herrada" },
    { value: "La Manga", label: "La Manga" },
    { value: "La Manga Club", label: "La Manga Club" },
    { value: "La Manga Del Mar Menor", label: "La Manga Del Mar Menor" },
    { value: "La Marina / El Pinet", label: "La Marina / El Pinet" },
    { value: "La Marquesa Golf", label: "La Marquesa Golf" },
    { value: "La Mata", label: "La Mata" },
    { value: "La Nucía", label: "La Nucía" },
    { value: "La Pinilla", label: "La Pinilla" },
    { value: "La Rambla", label: "La Rambla" },
    { value: "La Sabatera", label: "La Sabatera" },
    { value: "La Serena Golf", label: "La Serena Golf" },
    { value: "La Torre De La Horadada", label: "La Torre De La Horadada" },
    { value: "La Veleta", label: "La Veleta" },
    { value: "La Zenia", label: "La Zenia" },
    { value: "Lago Jardín II", label: "Lago Jardín II" },
    { value: "Las Colinas Golf", label: "Las Colinas Golf" },
    { value: "Las Esperanzas", label: "Las Esperanzas" },
    { value: "Las Filipinas", label: "Las Filipinas" },
    { value: "Las Heredades", label: "Las Heredades" },
    { value: "Las Higuericas", label: "Las Higuericas" },
    { value: "Las Marinas", label: "Las Marinas" },
    { value: "Las Marinas km 2.5", label: "Las Marinas km 2.5" },
    { value: "Las Palas", label: "Las Palas" },
    { value: "Lel", label: "Lel" },
    { value: "Levante", label: "Levante" },
    { value: "Lo Marabú", label: "Lo Marabú" },
    { value: "Lo Pagan", label: "Lo Pagan" },
    { value: "Lo Romero Golf", label: "Lo Romero Golf" },
    { value: "Loma Alta", label: "Loma Alta" },
    { value: "Lomas de Cabo Roig", label: "Lomas de Cabo Roig" },
    { value: "Lomas de Campoamor", label: "Lomas de Campoamor" },
    { value: "Los Altos", label: "Los Altos" },
    { value: "Los Altos", label: "Los Altos" },
    { value: "Los Antolinos", label: "Los Antolinos" },
    { value: "Los Balcones", label: "Los Balcones" },
    { value: "Los Cuarteros", label: "Los Cuarteros" },
    { value: "Los Locos", label: "Los Locos" },
    { value: "Los Narejos", label: "Los Narejos" },
    { value: "Los Nietos playa", label: "Los Nietos playa" },
    { value: "Los Plazas", label: "Los Plazas" },
    { value: "Manzanera", label: "Manzanera" },
    { value: "Mar De Cristal", label: "Mar De Cristal" },
    { value: "Maryvilla", label: "Maryvilla" },
    { value: "Mil Palmeras", label: "Mil Palmeras" },
    { value: "Monte Azul", label: "Monte Azul" },
    { value: "Montezenia", label: "Montezenia" },
    { value: "Mutxamel", label: "Mutxamel" },
    { value: "Nou Nazareth", label: "Nou Nazareth" },
    { value: "Nueva Ribera", label: "Nueva Ribera" },
    { value: "Orxeta", label: "Orxeta" },
    { value: "Panorama", label: "Panorama" },
    { value: "Paraiso", label: "Paraiso" },
    { value: "Parque de los leones", label: "Parque de los leones" },
    { value: "Parque del doce", label: "Parque del doce" },
    { value: "Partida Barranquets", label: "Partida Barranquets" },
    { value: "Partida Garduix", label: "Partida Garduix" },
    { value: "PAU 1", label: "PAU 1" },
    { value: "PAU 26", label: "PAU 26" },
    { value: "PAU 8", label: "PAU 8" },
    { value: "PAU1", label: "PAU1" },
    { value: "Pilar de la Horadada", label: "Pilar de la Horadada" },
    { value: "Pinar de Campoverde", label: "Pinar de Campoverde" },
    { value: "Pinomar", label: "Pinomar" },
    { value: "Playa de El Cura", label: "Playa de El Cura" },
    { value: "Playa de La Almadraba", label: "Playa de La Almadraba" },
    { value: "Playa de La Fustera", label: "Playa de La Fustera" },
    { value: "Playa de Levante", label: "Playa de Levante" },
    { value: "Playa de los Locos", label: "Playa de los Locos" },
    { value: "Playa del Alamillo", label: "Playa del Alamillo" },
    { value: "Playa del Bol", label: "Playa del Bol" },
    { value: "Playa del Cura", label: "Playa del Cura" },
    { value: "Playa Del Espejo", label: "Playa Del Espejo" },
    { value: "Playa del Hornillo", label: "Playa del Hornillo" },
    { value: "Playa del Torres", label: "Playa del Torres" },
    { value: "Playa Deveses", label: "Playa Deveses" },
    { value: "Playa Flamenca", label: "Playa Flamenca" },
    { value: "Playa Fustera", label: "Playa Fustera" },
    { value: "Playa Honda", label: "Playa Honda" },
    { value: "Playa La Fossa", label: "Playa La Fossa" },
    { value: "Playa Les Torres", label: "Playa Les Torres" },
    { value: "Playa Macenas (Mojácar)", label: "Playa Macenas (Mojácar)" },
    { value: "Playa Poniente", label: "Playa Poniente" },
    { value: "Playa Tamarit", label: "Playa Tamarit" },
    { value: "Playa Villananitos", label: "Playa Villananitos" },
    { value: "Polideportivo", label: "Polideportivo" },
    { value: "Polop Hills", label: "Polop Hills" },
    { value: "Poniente", label: "Poniente" },
    { value: "Pueblo", label: "Pueblo" },
    { value: "Puerta de Hierro", label: "Puerta de Hierro" },
    { value: "Puerto", label: "Puerto" },
    { value: "Puerto Azul", label: "Puerto Azul" },
    { value: "Puerto Denia", label: "Puerto Denia" },
    { value: "Puig Campana Golf", label: "Puig Campana Golf" },
    { value: "Punta Prima", label: "Punta Prima" },
    { value: "Racó Del Galeno", label: "Racó Del Galeno" },
    { value: "Riomar", label: "Riomar" },
    { value: "Roda Golf", label: "Roda Golf" },
    { value: "Rojales", label: "Rojales" },
    { value: "Roldán", label: "Roldán" },
    { value: "San Agustín-PAU 2", label: "San Agustín-PAU 2" },
    { value: "San Blas", label: "San Blas" },
    { value: "San Fernando", label: "San Fernando" },
    { value: "San Fulgencio", label: "San Fulgencio" },
    { value: "San Juan Alicante", label: "San Juan Alicante" },
    { value: "San Juan De Los Terreros", label: "San Juan De Los Terreros" },
    { value: "San Pedro Del Pinatar", label: "San Pedro Del Pinatar" },
    { value: "Santa Clara", label: "Santa Clara" },
    { value: "Santa Rosalia Lake and Life Resort", label: "Santa Rosalia Lake and Life Resort" },
    { value: "Santa Rosalia Lake And Life Resort", label: "Santa Rosalia Lake And Life Resort" },
    { value: "Santiago De La Ribera", label: "Santiago De La Ribera" },
    { value: "Sea Hills", label: "Sea Hills" },
    { value: "Seascape", label: "Seascape" },
    { value: "Sector 3", label: "Sector 3" },
    { value: "Serena Golf", label: "Serena Golf" },
    { value: "Sierra Altea", label: "Sierra Altea" },
    { value: "Sierra Cortina", label: "Sierra Cortina" },
    { value: "Sierra de Altea", label: "Sierra de Altea" },
    { value: "Sucina", label: "Sucina" },
    { value: "Torre De La Horadada", label: "Torre De La Horadada" },
    { value: "Torre del Rame", label: "Torre del Rame" },
    { value: "Torre del Rico", label: "Torre del Rico" },
    { value: "Torre Guil", label: "Torre Guil" },
    { value: "Torre-pacheco", label: "Torre-pacheco" },
    { value: "Torreblanca", label: "Torreblanca" },
    { value: "Torrepacheco", label: "Torrepacheco" },
    { value: "Torreta Florida", label: "Torreta Florida" },
    { value: "Torretas", label: "Torretas" },
    { value: "Urb. Don Mar", label: "Urb. Don Mar" },
    { value: "Urb. Kalendas", label: "Urb. Kalendas" },
    { value: "Urb. La Marina", label: "Urb. La Marina" },
    { value: "Urb. La Quinta", label: "Urb. La Quinta" },
    { value: "Urbaniz La Montañosa", label: "Urbaniz La Montañosa" },
    { value: "urbanizacion", label: "urbanizacion" },
    { value: "Urbanizaciones", label: "Urbanizaciones" },
    { value: "Valle Del Sol", label: "Valle Del Sol" },
    { value: "Veneziola", label: "Veneziola" },
    { value: "Vera Playa", label: "Vera Playa" },
    { value: "Verde Pino", label: "Verde Pino" },
    { value: "Villamartín", label: "Villamartín" },
    { value: "Villananitos", label: "Villananitos" },
    { value: "Villanueva del Rio Segura", label: "Villanueva del Rio Segura" },
    { value: "Villas de la Romana", label: "Villas de la Romana" },
    { value: "VistaBella Golf", label: "VistaBella Golf" },
    { value: "Xeresa Del Monte", label: "Xeresa Del Monte" },
    { value: "Yecla", label: "Yecla" },
    { value: "Zona de Poniente", label: "Zona de Poniente" },

  ],

  provience: [
    { value: "Alicante", label: "Alicante" },
    { value: "Almería", label: "Almería" },
    { value: "Baleares-Menorca", label: "Baleares-Menorca" },
    { value: "Murcia", label: "Murcia" },
    { value: "Valencia", label: "Valencia" },
  ],
  type: [
    { value: "Apartment / flat", label: "Apartment / flat" },
    { value: "Bungalow", label: "Bungalow" },
    { value: "Duplex", label: "Duplex" },
    { value: "Penthouse", label: "Penthouse" },
    { value: "Townhouse", label: "Townhouse" },
    { value: "Villa", label: "Villa" },
  ],
  price: [

    { value: 200000, label: "200.000 €" },
    { value: 400000, label: "400.000 €" },
    { value: 600000, label: "600.000 €" },
    { value: 800000, label: "800.000 €" },
    { value: 1000000, label: "1.000.000 €" },
    { value: 1200000, label: "1.200.000 €" },
    { value: 1400000, label: "1.400.000 €" },
    { value: 1600000, label: "1.600.000 €" },
    { value: 1800000, label: "1.800.000 €" },
    { value: 2000000, label: "2.000.000 €" },
    { value: 3000000, label: "+3.000.000 €" },
    { value: 50000000, label: "50.000.000 €" },
    { value: 100000000, label: "100.000.000€" },
    { value: 150000000, label: "150.000.000 €" },
    { value: 200000000, label: "200.000.000 €" },
    { value: 250000000, label: "250.000.000 €" },
    { value: 300000000, label: "300.000.000 €" },
    { value: 350000000, label: "350.000.000 €" },
    { value: 400000000, label: "400.000.000 €" },
    { value: 450000000, label: "450.000.000 €" },
    { value: 500000000, label: "500.000.000 €" },
    { value: 550000000, label: "550.000.000 €" },
    { value: 600000000, label: "600.000.000 €" },
    { value: 650000000, label: "650.000.000 €" },
    { value: 700000000, label: "700.000.000 €" },
    { value: 1000000000, label: "+1.000.000.000 €" },

  ],
  oriantation:[
    { value: "North", label: "North" },
    { value: "Northeast", label: "Northeast" },
    { value: "East", label: "East" },
    { value: "South east", label: "South east" },
    { value: "South", label: "South" },
    { value: "Southwest", label: "Southwest" },
    { value: "West", label: "West" },
    { value: "Northwest", label: "Northwest" },
  ]

}