import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageProviderWrapper from "./LanguageProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cookies } from "next/headers";
import { FavoriteProvider } from "@/context/FavoriteContext";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const lang = cookieStore.get("lang")?.value || "EN";


  return (
    <html lang={lang.toLowerCase()}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProviderWrapper initialLang={lang}>
          <FavoriteProvider>
            {children}
          </FavoriteProvider>
        </LanguageProviderWrapper>
      </body>
    </html>
  );
}
